/* Classic scripts intentionally work without a server or network. */
(function(){'use strict';
 const M=window.KanbaamModel,S=window.KanbaamStorage,$=s=>document.querySelector(s);
 let local;try{local=window.localStorage;}catch(e){local={getItem(){throw e;},setItem(){throw e;}};}
 const store=S.create(local,M),initial=store.load();let state=initial.state,browserError=initial.error||'',fileError='',actionError='';
 let editingProject=null,editingTask=null,viewingTask=null,dragId=null,filter='',priority='all';
 const labels={backlog:'Backlog',progress:'In progress',review:'Review',done:'Done'};
 const reduce=matchMedia('(prefers-reduced-motion: reduce)'),dark=matchMedia('(prefers-color-scheme: dark)');
 const animate=()=>state.settings.motion&&!reduce.matches;
 const project=()=>state.projects.find(p=>p.id===state.activeProjectId);
 const json=()=>JSON.stringify(state,null,2);
 const writer=S.writer(info=>{fileError=info.error||'';$('#file-status').textContent=info.error||(info.linked?(info.pending?'Saving linked file…':'Linked: '+info.name+' · up to date'):'No file linked.');$('#retry-file').hidden=!info.error;$('#disconnect-file').hidden=!info.linked;renderNotice();});
 function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;}
 function button(text,cls,click,label){const b=el('button',cls,text);b.type='button';b.onclick=click;if(label)b.setAttribute('aria-label',label);return b;}
 function tagChip(name){const c=el('span','tag',name);let h=0;for(let i=0;i<name.length;i++)h=(h*31+name.charCodeAt(i))%360;c.style.setProperty('--tag-h',h);return c;}
 function tagRow(t,cls){const row=el('span',cls);t.tags.forEach(name=>row.append(tagChip(name)));return row;}
 function announce(text){$('#announcement').textContent='';requestAnimationFrame(()=>$('#announcement').textContent=text);}
 function renderNotice(){const text=[browserError,fileError,actionError].filter(Boolean).join(' ');$('#notice').hidden=!text;$('#notice').textContent=text;$('#save-status').textContent=browserError?'Not saved in browser · export a backup':'Saved in this browser';$('#save-status').classList.toggle('error',!!browserError);}
 function persist(){try{store.save(state);browserError='';}catch(e){browserError=e.message+' Changes are only in memory; export a backup before closing.';}writer.enqueue(json());renderNotice();}
 function applyTheme(){const root=document.documentElement;root.dataset.accent=state.settings.accent;root.dataset.dark=String(state.settings.mode==='dark'||(state.settings.mode==='system'&&dark.matches));root.dataset.motion=String(animate());$('#theme-mode').value=state.settings.mode;$('#motion').checked=state.settings.motion;document.querySelectorAll('[name=accent]').forEach(n=>n.checked=n.value===state.settings.accent);}
 dark.addEventListener('change',applyTheme);reduce.addEventListener('change',applyTheme);
 function rects(){return new Map([...document.querySelectorAll('.task-card')].map(n=>[n.dataset.id,n.getBoundingClientRect()]));}
 function flip(before){if(!animate())return;document.querySelectorAll('.task-card').forEach((n,index)=>{const old=before.get(n.dataset.id),r=n.getBoundingClientRect();if(old){const dx=old.left-r.left,dy=old.top-r.top;if(dx||dy)n.animate([{transform:`translate(${dx}px,${dy}px)`},{transform:'translate(0,0)'}],{duration:420,easing:'cubic-bezier(.16,1,.3,1)'});}else n.animate([{opacity:0,transform:'translateY(16px) scale(.97)'},{opacity:1,transform:'none'}],{duration:350,delay:Math.min(index*35,250),easing:'cubic-bezier(.16,1,.3,1)',fill:'backwards'});});}
 function commit(action,message,doneId){const before=rects();try{action();actionError='';persist();render();flip(before);if(message)announce(message);if(doneId)celebrate(doneId);}catch(e){actionError=e.message;renderNotice();}}
 function focusCard(id,direction){const card=[...document.querySelectorAll('.task-card')].find(n=>n.dataset.id===id);const control=direction?card?.querySelector(`[data-direction="${direction}"]`):null;(control&&!control.disabled?control:card?.querySelector('.card-open'))?.focus({preventScroll:true});}
 function render(){
  applyTheme();const p=project();$('#projects').replaceChildren();state.projects.forEach(item=>{const b=button('','project-button',()=>selectProject(item.id));b.setAttribute('aria-current',String(p?.id===item.id));b.append(el('span','', '▤'),el('span','project-name',item.name),el('span','project-count',String(item.tasks.length)));$('#projects').append(b);});
  $('#breadcrumb').textContent=p?p.name:'Your boards';$('#project-title').textContent=p?p.name:'Room for your next idea.';$('#project-eyebrow').textContent=p?'YOUR PROJECT':'A LITTLE MORE DONE';$('#project-subtitle').textContent=p?'One thing at a time. Keep it moving.':'A clear place to see what’s next, what’s moving, and what’s done.';
  $('#welcome').hidden=!!p;['#project-actions','#board-tools','#board','#board-footer'].forEach(s=>$(s).hidden=!p);$('#board').replaceChildren();if(!p)return;
  const visible=p.tasks.filter(t=>(priority==='all'||t.priority===priority)&&(!filter||(t.title+' '+t.description+' '+t.tags.join(' ')).toLowerCase().includes(filter)));
  $('#task-total').textContent=filter||priority!=='all'?`${visible.length} of ${p.tasks.length}`:String(p.tasks.length);$('#clear-filters').hidden=!filter&&priority==='all';
  for(const status of M.statuses){const lane=el('section','lane');lane.dataset.status=status;lane.setAttribute('aria-label',labels[status]);const heading=el('div','lane-heading');heading.append(el('span','lane-dot'),el('h2','',labels[status]),el('span','lane-count',String(visible.filter(t=>t.status===status).length)),button('+','icon-button',()=>openTask(null,status),'Add task to '+labels[status]));lane.append(heading);const cards=el('div','lane-cards');
   const tasks=visible.filter(t=>t.status===status);tasks.forEach(t=>cards.append(renderCard(t,p)));if(!tasks.length)cards.append(el('p','lane-empty',filter||priority!=='all'?'No matching tasks':status==='backlog'?'A place for what’s next.':status==='done'?'Good things take a little doing.':'Ready when you are.'));
   lane.append(cards,button('+ Add task','lane-add',()=>openTask(null,status),'Add task to '+labels[status]));lane.ondragover=e=>{if(!dragId)return;e.preventDefault();e.dataTransfer.dropEffect='move';lane.classList.add('drag-over');};lane.ondragleave=e=>{if(!lane.contains(e.relatedTarget))lane.classList.remove('drag-over');};lane.ondrop=e=>{e.preventDefault();lane.classList.remove('drag-over');if(!dragId)return;const id=dragId;dragId=null;const others=p.tasks.filter(t=>t.status===status&&t.id!==id);const targets=[...cards.querySelectorAll('.task-card')].filter(n=>n.dataset.id!==id);const target=targets.find(n=>e.clientY<n.getBoundingClientRect().top+n.getBoundingClientRect().height/2);const index=target?others.findIndex(t=>t.id===target.dataset.id):others.length;move(id,status,index);};$('#board').append(lane);
  }
 }
 function renderCard(t,p){const card=el('article','task-card');card.dataset.id=t.id;card.draggable=true;const open=button('','card-open',()=>openView(t),'View task: '+t.title);open.append(el('span','card-title',t.title));if(t.description)open.append(el('span','card-description',t.description));if(t.tags.length)open.append(tagRow(t,'card-tags'));const meta=el('span','card-meta');meta.append(el('span','priority '+t.priority,t.priority[0].toUpperCase()+t.priority.slice(1)));if(t.link)meta.append(el('span','card-link-dot','link'));if(t.due){const date=new Date(t.due+'T12:00:00');const today=new Date();today.setHours(0,0,0,0);const due=el('span','due'+(date<today&&t.status!=='done'?' overdue':''),date.toLocaleDateString(undefined,{month:'short',day:'numeric',...(date.getFullYear()!==today.getFullYear()?{year:'numeric'}:{})}));due.title='Due '+t.due;meta.append(due);}open.append(meta);const controls=el('div','card-controls');controls.append(button('Edit','subtle card-edit',()=>openTask(t),'Edit task: '+t.title));const lane=p.tasks.filter(x=>x.status===t.status),index=lane.indexOf(t);
  for(const [dir,symbol,delta] of [['up','↑',-1],['down','↓',1]]){const b=button(symbol,'subtle',()=>{move(t.id,t.status,index+delta);focusCard(t.id,dir);},'Move '+t.title+' '+dir);b.dataset.direction=dir;b.disabled=dir==='up'?index===0:index===lane.length-1;controls.append(b);}card.append(open,controls);card.ondragstart=e=>{dragId=t.id;e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',t.id);requestAnimationFrame(()=>card.classList.add('dragging'));};card.ondragend=()=>{dragId=null;card.classList.remove('dragging');document.querySelectorAll('.drag-over').forEach(n=>n.classList.remove('drag-over'));};return card;
 }
 function move(id,status,index){const t=project().tasks.find(t=>t.id===id);const done=status==='done'&&t.status!=='done';commit(()=>M.moveTask(project(),id,status,index),'Task moved to '+labels[status],done?id:null);}
 function selectProject(id){if(id===state.activeProjectId)return;state.activeProjectId=id;filter='';priority='all';$('#search').value='';$('#priority-filter').value='all';persist();render();$('#board').classList.remove('project-enter');void $('#board').offsetWidth;$('#board').classList.add('project-enter');flip(new Map());announce('Opened '+project().name);}
 function show(dialog){dialog.querySelector('.form-error')?.replaceChildren();dialog.showModal();}
 function openProject(rename=false){editingProject=rename?project().id:null;$('#project-dialog-title').textContent=rename?'Rename project':'New project';$('#project-name').value=rename?project().name:'';show($('#project-dialog'));$('#project-name').focus();}
 function openTask(task,status='backlog'){$('#view-dialog').close();editingTask=task?.id??null;const f=$('#task-form');f.reset();f.elements.title.value=task?.title??'';f.elements.description.value=task?.description??'';f.elements.status.value=task?.status??status;f.elements.priority.value=task?.priority??'medium';f.elements.due.value=task?.due??'';f.elements.link.value=task?.link??'';f.elements.tags.value=(task?.tags??[]).join(', ');$('#task-dialog-title').textContent=task?'Task details':'New task';$('#delete-task').hidden=!task;show($('#task-dialog'));f.elements.title.focus();}
 function openView(task){viewingTask=task.id;$('#view-status-tag').textContent=labels[task.status];$('#view-status-tag').dataset.status=task.status;$('#view-title').textContent=task.title;const desc=$('#view-description');desc.textContent=task.description||'No description yet.';desc.classList.toggle('empty',!task.description);$('#view-priority').textContent=task.priority[0].toUpperCase()+task.priority.slice(1);$('#view-due-row').hidden=!task.due;if(task.due)$('#view-due').textContent=new Date(task.due+'T12:00:00').toLocaleDateString(undefined,{year:'numeric',month:'long',day:'numeric'});$('#view-link-row').hidden=!task.link;if(task.link){const a=$('#view-link');a.href=task.link;a.textContent=task.link;}$('#view-tags-row').hidden=!task.tags.length;$('#view-tags').replaceChildren(...task.tags.map(tagChip));show($('#view-dialog'));$('#view-edit').focus();}
 function confirmAction(title,message,label='Confirm'){return new Promise(resolve=>{const d=$('#confirm-dialog');$('#confirm-title').textContent=title;$('#confirm-message').textContent=message;$('#confirm-button').textContent=label;d.returnValue='cancel';d.addEventListener('close',()=>resolve(d.returnValue==='confirm'),{once:true});d.showModal();});}
 document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
 ['#add-project','#new-project','#start-project'].forEach(s=>$(s).onclick=()=>openProject());$('#rename-project').onclick=()=>openProject(true);$('#add-task').onclick=()=>openTask(null);$('#view-edit').onclick=()=>{const t=project()?.tasks.find(t=>t.id===viewingTask);if(t)openTask(t);};
 $('#project-form').onsubmit=e=>{e.preventDefault();try{const name=$('#project-name').value;if(editingProject)M.renameProject(state,editingProject,name);else M.addProject(state,name);persist();render();$('#project-dialog').close();flip(new Map());announce('Project saved');}catch(error){$('#project-form .form-error').textContent=error.message;}};
 $('#delete-project').onclick=async()=>{const p=project();if(await confirmAction('Delete project?',`“${p.name}” and all its tasks will be permanently removed. Export a backup first if you want to keep a copy.`,'Delete project'))commit(()=>M.deleteProject(state,p.id),'Project deleted');};
 $('#task-form').onsubmit=e=>{e.preventDefault();const f=e.currentTarget;try{const before=rects(),old=project().tasks.find(t=>t.id===editingTask);const previous=old?.status;const t=M.saveTask(project(),{id:editingTask,title:f.elements.title.value,description:f.elements.description.value,priority:f.elements.priority.value,status:f.elements.status.value,due:f.elements.due.value,link:f.elements.link.value,tags:f.elements.tags.value});persist();render();$('#task-dialog').close();flip(before);if(t.status==='done'&&previous!=='done')celebrate(t.id);focusCard(t.id);announce('Task saved');}catch(error){$('#task-form .form-error').textContent=error.message;}};
 $('#delete-task').onclick=async()=>{const id=editingTask;if(await confirmAction('Delete task?','This task will be permanently removed.','Delete task')){$('#task-dialog').close();commit(()=>M.deleteTask(project(),id),'Task deleted');}};
 $('#search').oninput=e=>{filter=e.target.value.trim().toLowerCase();render();};$('#priority-filter').onchange=e=>{priority=e.target.value;render();};$('#clear-filters').onclick=()=>{filter='';priority='all';$('#search').value='';$('#priority-filter').value='all';render();};
 $('#sample-project').onclick=()=>commit(()=>{const p=M.addProject(state,'A fresh start · sample');[{title:'Make this board your own',description:'This is an optional sample project. Rename it, change a task, or delete it and start fresh.',priority:'low',tags:['Content','AI Project']},{title:'Gather the loose ends',description:'Get ideas out of your head. Add a task for each next step.',status:'backlog',tags:['Design']},{title:'Give one thing your attention',description:'Drag this card forward, or open it and change its status.',status:'progress',priority:'high',tags:['AI Project','Design']},{title:'Take a second look',description:'A little space to check the details before calling it done.',status:'review',tags:['Content']},{title:'Make room to begin',description:'You opened a board. That counts.',status:'done',priority:'low',tags:['Technical Content']}].forEach(t=>M.saveTask(p,t));},'Sample project created');
 const swatches={vermilion:'#b8442c',forest:'#377053',cobalt:'#3562aa',plum:'#865072',ochre:'#8c641d'};M.accents.forEach(accent=>{const label=el('label','accent-option'),input=document.createElement('input');input.type='radio';input.name='accent';input.value=accent;input.setAttribute('aria-label',accent[0].toUpperCase()+accent.slice(1));input.onchange=()=>{state.settings.accent=accent;applyTheme();persist();};const swatch=el('span');swatch.style.setProperty('--swatch',swatches[accent]);swatch.title=accent;label.append(input,swatch);$('#accent-options').append(label);});
 $('#settings-open').onclick=()=>show($('#settings-dialog'));$('#theme-mode').onchange=e=>{state.settings.mode=e.target.value;applyTheme();persist();};$('#motion').onchange=e=>{state.settings.motion=e.target.checked;applyTheme();persist();};
 function download(raw,name){const url=URL.createObjectURL(new Blob([raw],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 $('#export').onclick=()=>{download(json(),'kanbaam.json');announce('Workspace export downloaded');};$('#export-backup').onclick=()=>{try{const raw=local.getItem(S.BACKUP);if(raw===null)throw Error('No previous backup exists yet.');download(raw,'kanbaam-previous-backup.json');}catch(e){actionError=e.message;renderNotice();$('#file-status').textContent=e.message;}};
 async function readFile(file){if(file.size>S.MAX_BYTES)throw Error('Workspace is too large (5 MB maximum).');return store.parse(await file.text());}
 async function replaceWorkspace(next,name){if(!await confirmAction('Replace workspace?',`Load “${name}” and replace all current projects and settings? The previous browser data will be backed up. Any linked file will be disconnected.`,'Replace workspace'))return false;store.replace(next);writer.disconnect();state=next;browserError='';actionError='';filter='';priority='all';$('#search').value='';$('#priority-filter').value='all';render();renderNotice();flip(new Map());announce('Workspace imported');return true;}
 function fileFailure(e){if(e.name==='AbortError')return;actionError=e.message;$('#file-status').textContent=e.message;renderNotice();}
 $('#import').onclick=()=>$('#import-file').click();$('#import-file').onchange=async e=>{const f=e.target.files[0];e.target.value='';if(!f)return;try{await replaceWorkspace(await readFile(f),f.name);}catch(error){fileFailure(error);}};
 const supported=typeof window.showSaveFilePicker==='function'&&typeof window.showOpenFilePicker==='function';$('#file-capability').textContent=supported?'This browser can save changes directly to a JSON file you choose. Browser storage remains your fallback.':'Direct file linking is unavailable in this browser. Use Export JSON and Import JSON instead; your browser workspace still saves automatically.';$('#create-file').disabled=!supported;$('#open-file').disabled=!supported;
 const pickerTypes=[{description:'Kanbaam JSON workspace',accept:{'application/json':['.json']}}];
 $('#create-file').onclick=async()=>{try{const handle=await window.showSaveFilePicker({suggestedName:'kanbaam.json',types:pickerTypes});writer.connect(handle);await writer.enqueue(json());}catch(e){fileFailure(e);}};
 $('#open-file').onclick=async()=>{try{const [handle]=await window.showOpenFilePicker({types:pickerTypes,multiple:false});const next=await readFile(await handle.getFile());if(await replaceWorkspace(next,handle.name))writer.connect(handle);}catch(e){fileFailure(e);}};
 $('#retry-file').onclick=()=>writer.retry(json());$('#disconnect-file').onclick=()=>writer.disconnect();
 function celebrate(id){if(!animate())return;const card=[...document.querySelectorAll('.task-card')].find(n=>n.dataset.id===id);if(!card)return;const r=card.getBoundingClientRect();if(r.left>innerWidth||r.right<0)return;for(let i=0;i<16;i++){const p=el('i','particle');p.style.left=r.left+r.width/2+'px';p.style.top=r.top+20+'px';document.body.append(p);const angle=Math.PI*2*i/16,reach=40+Math.random()*55;const a=p.animate([{opacity:1,transform:'translate(0,0) rotate(0deg)'},{opacity:0,transform:`translate(${Math.cos(angle)*reach}px,${Math.sin(angle)*reach+35}px) rotate(${i*47}deg)`}],{duration:600+Math.random()*250,easing:'cubic-bezier(.12,.65,.25,1)'});a.onfinish=()=>p.remove();}}
 window.addEventListener('beforeunload',e=>{if(browserError||writer.pending||writer.error){e.preventDefault();e.returnValue='';}});
 render();renderNotice();flip(new Map());
 window.Kanbaam={getState:()=>structuredClone(state),storageKey:S.KEY};
})();
