const fs = require('node:fs');
const path = require('node:path');
const lucide = require('lucide');
const names = ['Archive', 'Plus', 'X', 'Pencil', 'Trash2', 'ArrowUp', 'ArrowDown', 'ArrowUpDown', 'ChevronLeft', 'ChevronRight', 'PanelLeftClose', 'PanelLeftOpen', 'Search', 'SlidersHorizontal', 'CalendarDays', 'Link', 'EllipsisVertical', 'Sun', 'Moon', 'Settings', 'Folder', 'Rocket', 'Briefcase', 'Palette', 'CodeXml', 'BookOpen', 'House', 'Heart', 'Star', 'Lightbulb', 'Target', 'Leaf', 'Coffee', 'Music', 'Camera', 'Plane', 'GraduationCap'];
const target = path.resolve(__dirname, '../assets');
fs.mkdirSync(target, { recursive: true });
const icons = Object.fromEntries(names.map(name => [name, lucide[name]]));
fs.writeFileSync(path.join(target, 'icons.js'), '// Generated by scripts/build-icons.cjs from Lucide. See lucide-LICENSE.\nwindow.KanbaamIcons = ' + JSON.stringify(icons) + ';\n');
fs.copyFileSync(require.resolve('lucide').replace(/dist[\\/].*$/, 'LICENSE'), path.join(target, 'lucide-LICENSE'));
